import mongoose from "mongoose";

const certificateSchema = new mongoose.Schema({
  id: { type: String, required: true }, // Certificate ID (generated by the parser)
  slug: { type: String, required: true }, // Program slug (e.g., 'responsive-web-design-v9')
  title: { type: String, required: true }, // Display title of the certificate
  url: { type: String, required: true }, // Verification URL linking to freecodecamp.org
});

// The third argument 'certificates' binds the model to the certificates collection
export const Certificate = mongoose.model(
  "Certificate",
  certificateSchema,
  "certificates",
);
